on:
  schedule:
    - cron: '0 8 * * *'
jobs:
  run-jar-job:
    runs-on: ubuntu-latest
    steps:
      - run: java -jar target/xueXiT-1.jar

  job2:
    runs-on: windows-latest
    steps:
      - run: node --version
